services:
  gosplash:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17.4-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .postgres.env
    volumes:
      - ./data:/var/lib/pgsql/data
    ports:
      - 5432:5432
